require 'build_and_run_config.cpp_build_and_run'
require 'build_and_run_config.c_build_and_run'
require 'build_and_run_config.tex_build_and_run'
require 'build_and_run_config.fpc_build_and_run'
require 'build_and_run_config.solidity'
